### ISSUE TITLE
If VDU deployment fails, VNFR goes to ERROR 

### ISSUE THREAD

**Issue by lorenzotomasini** [openbaton/NFVO#101]
When NFVO allocate resources, in case of a VNFR with more than one VDU, if one VDU fails allocating resources, check if the whole VNFR must go to ERROR or not

**Comment by lorenzotomasini** [comment]
@mpauls is this fixed now?

**Comment by mpauls** [comment]
no. not yet fixed. Question is how to handle this situation? How to perform a this check? Where do we know from if the failing VDU was crucial or not? I think, if any VDU deployment fails, the entire VNFR goes to error. Is already like this.

**Comment by lorenzotomasini** [comment]
and in the later case, if the nsr is removed also all the errored VMs are removed?

**Comment by mpauls** [comment]
yes. deployment stops once any VM errored and is also added to the list of VNFC Instance besides the ones which were already launched correctly. All VMs spawned by the NFVO are in the list of VNFC instances in this case.

**Comment by gc4rella** [comment]
can be closed?

**Comment by lorenzotomasini** [comment]
Depends if we decide that VDUs will be simply multiple instances of the same VNF or we want to add also the possibility of VDU dependencies. in the first case, the issue is still open in the second the issue does not exist and can be closed

**Comment by marcellom** [comment]
Following the ETSI specification (see section 6.3 http://www.etsi.org/deliver/etsi_gs/NFV-SWA/001_099/001/01.01.01_60/gs_NFV-SWA001v010101p.pdf) a VNF can be made by different VDUs and each VDU can have multiple (identical) VNF components. However, dependencies are not discussed.
